In [1]:
import pandas as pd

# Data Cleaning

In [17]:
sales=pd.read_excel(
    "medical_store_sales_data.xlsx",
    sheet_name="Sales_Data"
)
medicine=pd.read_excel(
    "medical_store_sales_data.xlsx",
    sheet_name="Medicine_Master"
)

In [30]:
medicine.head()

,Medicine Name,Dosage Form,Category,Unit Price (₹),Reorder Level,Supplier,Current Stock (Units),Expiry Monitoring
0,Paracetamol 500mg,Tablet,Pain Relief,2.5,80,Abbott,42,Normal
1,Dolo 650,Tablet,Pain Relief,3.2,120,Dr. Reddy's,51,Normal
2,Crocin Advance,Tablet,Pain Relief,3.0,60,Alkem,152,Normal
3,Azithromycin 500mg,Tablet,Antibiotic,12.5,35,Sun Pharma,148,Normal
4,Amoxicillin 500mg,Capsule,Antibiotic,8.5,40,Sun Pharma,103,Normal

In [19]:
sales.head()

,Date,Invoice No,Medicine Name,Dosage Form,Category,Unit Price (₹),Quantity Sold,Gross Sales (₹),Discount %,Discount (₹),Net Sales Before GST (₹),GST %,GST (₹),Total Bill (₹),Payment Mode,Customer Type,Day,Month
0,2026-06-15,INV-10001,Cough Syrup 100ml,Syrup,Cough & Cold,85.0,2,170.0,0,0.0,170.0,5,8.50,178.50,UPI,Walk-in,Monday,June
1,2026-06-15,INV-10002,ORS Orange,Sachet,Hydration,20.0,2,40.0,0,0.0,40.0,5,2.00,42.00,UPI,Walk-in,Monday,June
2,2026-06-15,INV-10003,Metformin 500mg,Tablet,Diabetes,1.5,2,3.0,0,0.0,3.0,5,0.15,3.15,UPI,Walk-in,Monday,June
3,2026-06-15,INV-10004,Electral ORS,Sachet,Hydration,20.0,6,120.0,5,6.0,114.0,5,5.70,119.70,UPI,Walk-in,Monday,June
4,2026-06-15,INV-10005,Pantoprazole 40mg,Tablet,Gastro,4.5,3,13.5,0,0.0,13.5,5,0.68,14.18,Cash,Walk-in,Monday,June

In [23]:
sales.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3388 entries, 0 to 3387
Data columns (total 18 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Date                      3388 non-null   datetime64[ns]
 1   Invoice No                3388 non-null   object
 2   Medicine Name             3388 non-null   object
 3   Dosage Form               3388 non-null   object
 4   Category                  3388 non-null   object
 5   Unit Price (₹)            3388 non-null   float64
 6   Quantity Sold             3388 non-null   int64
 7   Gross Sales (₹)           3388 non-null   float64
 8   Discount %                3388 non-null   int64
 9   Discount (₹)              3388 non-null   float64
 10  Net Sales Before GST (₹)  3388 non-null   float64
 11  GST %                     3388 non-null   int64
 12  GST (₹)                   3388 non-null   float64
 13  Total Bill (₹)            3388 non-null   float64
 14  Payment Mode              3388 non-null   object
 15  Customer Type             3388 non-null   object
 16  Day                       3388 non-null   object
 17  Month                     3388 non-null   object
dtypes: datetime64[ns](1), float64(6), int64(3), object(8)
memory usage: 476.6+ KB

In [24]:
sales.isnull().sum()

Date                        0
Invoice No                  0
Medicine Name               0
Dosage Form                 0
Category                    0
Unit Price (₹)              0
Quantity Sold               0
Gross Sales (₹)             0
Discount %                  0
Discount (₹)                0
Net Sales Before GST (₹)    0
GST %                       0
GST (₹)                     0
Total Bill (₹)              0
Payment Mode                0
Customer Type               0
Day                         0
Month                       0
dtype: int64

In [25]:
sales.describe()

,Date,Unit Price (₹),Quantity Sold,Gross Sales (₹),Discount %,Discount (₹),Net Sales Before GST (₹),GST %,GST (₹),Total Bill (₹)
count,3388,3388.000000,3388.000000,3388.000000,3388.000000,3388.000000,3388.000000,3388.000000,3388.000000,3388.000000
mean,2026-07-29 21:47:23.447461376,25.337692,2.488489,62.495602,0.757674,0.488377,62.007226,9.035419,5.505375,67.512600
min,2026-06-15 00:00:00,1.500000,1.000000,1.500000,0.000000,0.000000,1.430000,5.000000,0.070000,1.500000
25%,2026-07-07 00:00:00,2.800000,1.000000,5.000000,0.000000,0.000000,5.000000,5.000000,0.380000,5.430000
50%,2026-07-31 00:00:00,4.000000,2.000000,11.100000,0.000000,0.000000,11.000000,5.000000,0.960000,11.800000
75%,2026-08-22 00:00:00,20.000000,3.000000,44.000000,2.000000,0.050000,44.000000,12.000000,4.000000,49.337500
max,2026-09-12 00:00:00,145.000000,8.000000,1160.000000,5.000000,58.000000,1160.000000,18.000000,208.800000,1368.800000
std,NaN,40.785632,1.555636,127.032566,1.392125,2.373126,125.997377,4.885997,13.426506,137.669159

In [35]:
sales.duplicated().sum()

np.int64(0)

In [36]:
sales.columns

Index(['Date', 'Invoice_No', 'Medicine_Name', 'Dosage_Form', 'Category',
       'Unit_Price_(₹)', 'Quantity_Sold', 'Gross_Sales_(₹)', 'Discount_%',
       'Discount_(₹)', 'Net_Sales_Before_GST_(₹)', 'GST_%', 'GST_(₹)',
       'Total_Bill_(₹)', 'Payment_Mode', 'Customer_Type', 'Day', 'Month'],
      dtype='object')

In [37]:
sales.columns=sales.columns.str.replace(" ","_")

In [38]:
sales.columns

Index(['Date', 'Invoice_No', 'Medicine_Name', 'Dosage_Form', 'Category',
       'Unit_Price_(₹)', 'Quantity_Sold', 'Gross_Sales_(₹)', 'Discount_%',
       'Discount_(₹)', 'Net_Sales_Before_GST_(₹)', 'GST_%', 'GST_(₹)',
       'Total_Bill_(₹)', 'Payment_Mode', 'Customer_Type', 'Day', 'Month'],
      dtype='object')

In [42]:
sales=sales.drop("Year",axis=1)

In [43]:
sales.columns

Index(['Date', 'Invoice_No', 'Medicine_Name', 'Dosage_Form', 'Category',
       'Unit_Price_(₹)', 'Quantity_Sold', 'Gross_Sales_(₹)', 'Discount_%',
       'Discount_(₹)', 'Net_Sales_Before_GST_(₹)', 'GST_%', 'GST_(₹)',
       'Total_Bill_(₹)', 'Payment_Mode', 'Customer_Type', 'Day', 'Month'],
      dtype='object')

In [44]:
sales.head()

,Date,Invoice_No,Medicine_Name,Dosage_Form,Category,Unit_Price_(₹),Quantity_Sold,Gross_Sales_(₹),Discount_%,Discount_(₹),Net_Sales_Before_GST_(₹),GST_%,GST_(₹),Total_Bill_(₹),Payment_Mode,Customer_Type,Day,Month
0,2026-06-15,INV-10001,Cough Syrup 100ml,Syrup,Cough & Cold,85.0,2,170.0,0,0.0,170.0,5,8.50,178.50,UPI,Walk-in,Monday,June
1,2026-06-15,INV-10002,ORS Orange,Sachet,Hydration,20.0,2,40.0,0,0.0,40.0,5,2.00,42.00,UPI,Walk-in,Monday,June
2,2026-06-15,INV-10003,Metformin 500mg,Tablet,Diabetes,1.5,2,3.0,0,0.0,3.0,5,0.15,3.15,UPI,Walk-in,Monday,June
3,2026-06-15,INV-10004,Electral ORS,Sachet,Hydration,20.0,6,120.0,5,6.0,114.0,5,5.70,119.70,UPI,Walk-in,Monday,June
4,2026-06-15,INV-10005,Pantoprazole 40mg,Tablet,Gastro,4.5,3,13.5,0,0.0,13.5,5,0.68,14.18,Cash,Walk-in,Monday,June

In [45]:
sales.to_csv(
    "medical_clean_sales_data.csv",
    index=False
)